services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
    ports:
      - "3307:3306"
    volumes: #location of the container
      - symfonyTest:/var/lib/mysql
    networks: #if multiple machine
      - symfony_network
    restart: always

  #pasunod og run
  phpmyadmin:
    image: phpmyadmin:5.2
    container_name: qwepic
    depends_on:
      - mysql
    environment: 
      PMA_HOST: mysql
      PMA_USER: $MYSQL_USER
      PMA_PASSWORD: $MYSQL_PASSWORD
    ports:
      - "8080:80"
    networks:
      - symfony_network
    restart: always


volumes:
  symfonyTest:

networks:
  symfony_network: